version: '3.8'

services:
  database:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: gestionproduitbd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zongoyasminamonbebe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: spring-backend
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/gestionproduitbd
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: zongoyasminamonbebe
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: angular-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres-data: